name: Deploy to Uberspace

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, zip, gd, mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-dev --prefer-dist

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.4'

      - name: Install NPM dependencies
        run: npm install

      - name: Build frontend assets
        run: npm run build

      - name: Deploy to Uberspace
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.UBERSPACE_HOST }}
          REMOTE_USER: ${{ secrets.UBERSPACE_USER }}
          TARGET: ${{ secrets.UBERSPACE_DOCUMENT_ROOT }}
          EXCLUDE: "/.git/, /.github/, /node_modules/"

      - name: Run post-deployment commands on Uberspace
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UBERSPACE_HOST }}
          username: ${{ secrets.UBERSPACE_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.UBERSPACE_DOCUMENT_ROOT }}
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache