# Name of the GitHub Action
name: Deploy Frontend to GitHub Pages

# Run this workflow on every push to the 'main' branch
on:
  push:
    branches: [ "main" ] # Or "master" if that's your default branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Sets up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      # 3. Installs project dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Builds the Vue app for production
      - name: Build Static Files
        run: npm run build

      # 5. Deploys the built files to the 'gh-pages' branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # The directory to publish
          publish_branch: gh-pages # The branch to deploy to