# Name of the GitHub Action
name: Deploy Frontend to GitHub Pages

# Run this workflow on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # --- NEW STEP 1: Setup PHP Environment ---
      # We need PHP because the build process runs 'php artisan'
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Specify your PHP version
          extensions: mbstring, dom, fileinfo, xml
          coverage: none

      # --- NEW STEP 2: Install Composer Dependencies ---
      # This will create the 'vendor' directory and the missing 'autoload.php' file
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      # This step should now work correctly
      - name: Build Static Files
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages